<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>assets\Android-Logo-2008.ico</ApplicationIcon>
    <TargetPlatformVersion>10.0.26100.0</TargetPlatformVersion>
    <PackageIcon>Android-Logo-2008.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <NeutralLanguage>es-419</NeutralLanguage>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <FileVersion>1.0.0</FileVersion>
    <PackageReleaseNotes>Version inicial</PackageReleaseNotes>
    <PackageTags>adb, usb debug, android, wireless debug, sideload, apk, pair device</PackageTags>
    <Copyright>Setzer333</Copyright>
    <Company>Setzer333</Company>
    <Authors>Setzer333</Authors>
    <Title>AdbWirelessToolkitGUI</Title>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <PackageLicenseFile>Combined-License_2.txt</PackageLicenseFile>
    <Platforms>AnyCPU;x86;x64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'">
    <PlatformTarget>x86</PlatformTarget>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <PlatformTarget>x64</PlatformTarget>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="assets\Android-Logo-2008.ico" />
    <Resource Include="assets\Android-Logo-2008.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="LANGUAGES\**\*.xaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="assets\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="PlatformTools\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="assets\RUNTIME\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Update="assets\LICENCES\LICENSE-GPL3.rtf">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="assets\LICENCES\LICENSE-MIT.rtf">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="assets\LICENCES\Combined-License_2.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <Target Name="BuildInstaller" AfterTargets="Publish">
    <Exec Command="&quot;C:\Program Files\Inno Setup 7\ISCC.exe&quot; &quot;$(MSBuildProjectDirectory)\Installer\installer.iss&quot;" />
  </Target>

</Project>